root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# Array of commands to run before each build
pre_cmd = ["templ generate", "npx tailwindcss -i ./static/css/input.css -o ./static/css/styles.css"]
# Build command - use "." to build from current directory, Go will find main.go in cmd/server
cmd = "go build -o ./tmp/main.exe ./cmd/server"
# Array of commands to run after ^C
post_cmd = []
# Binary file yields from `cmd`
bin = "tmp/main.exe"
# Customize binary, can setup environment variables when run your app
full_bin = "./tmp/main.exe"
# Watch these filename extensions
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
# Ignore these filename extensions or directories
exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", "bin", "static"]
# Watch these directories if you specified
include_dir = []
# Watch these files
include_file = []
# Exclude files
exclude_file = []
# Exclude specific regular expressions
exclude_regex = ["_test\\.go", "_templ\\.go$"]
# Exclude unchanged files
exclude_unchanged = false
# Follow symlink for directories
follow_symlink = false
# This log file places in your tmp_dir
log = "errors.log"
# Poll files for changes instead of using fsnotify
poll = false
# Poll interval (defaults to the minimum interval of 500ms)
poll_interval = 0
# It's not necessary to trigger build each time file changes if it's too frequent
delay = 0
# Stop running old binary when build errors occur
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = "0s"
# Rerun binary or not
rerun = true
# Delay after each executions
rerun_delay = 500
# Add additional arguments when running binary (bin/full_bin)
args_bin = []

[log]
# Show log time
time = false
# Only show main log (hide request log)
main_only = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true